# Generated by Django 5.1 on 2024-12-15 19:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-sent_at',), 'verbose_name': 'contato', 'verbose_name_plural': 'contatos'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.AddField(
            model_name='contact',
            name='response',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='recebido em'),
            preserve_default=False,
        ),
    ]
