# Generated by Django 5.1 on 2024-11-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "inscricao",
                "verbose_name_plural": "inscrições",
            },
        ),
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
        ),
    ]
